[package]
name = "concert"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet", features = ["debug"] }
multitoken-io = { git = "https://github.com/gear-dapps/multitoken.git", tag = "0.3.4" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.5" }
hashbrown = "0.13"
concert-io = { path = "io" }

[dev-dependencies]
concert-state = { path = "state", features = ["binary-vendor"] }
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
gclient = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
tokio = "1"

[build-dependencies]
concert-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }

[features]
binary-vendor = []

[workspace]
members = ["state"]
