[package]
name = "concert"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git" }
concert-io = { path = "io" }
multitoken-io = { git = "https://github.com/gear-dapps/multitoken.git", tag = "0.3.1" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.0" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git" }
