[package]
name = "concert-io"
version = "0.1.2"
edition = "2021"

[dependencies]
gmeta.workspace = true
gstd.workspace = true
gear-lib.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
